apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-api
  template:
    metadata:
      labels:
        app: workflow-api
    spec:
      containers:
        - name: workflow-api
          image: workflow-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-api-service
spec:
  selector:
    app: workflow-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-service
  template:
    metadata:
      labels:
        app: orchestrator-service
    spec:
      containers:
        - name: orchestrator-service
          image: orchestrator-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: app-config

---

apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service-svc
spec:
  selector:
    app: orchestrator-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
